name: caching dependencies

on: [pull_request]
 
jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt 
        python -m playwright install 

    - name: Run tests
      run: |
        pytest test_elements.py

  test1:
    runs-on: ubuntu-latest  
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2  
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 
          python -m playwright install 
  
      - name: Run tests
        run: |
          pytest test_elements.py
