name: cafe_metrics

on: workflow_dispatch

jobs:
  Setup_Environment:
    runs-on: ubuntu-latest
    steps:
      # ✅ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        

      # ✅ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      # ✅ Install dependencies and create the virtual environment
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip tar

          # Create and activate the virtual environment
          python -m venv .venv
          
          # Validate environment creation
          if [ ! -d ".venv" ]; then
            echo "Failed to create .venv"
            exit 1
          fi
          
          source .venv/bin/activate
          pip install --upgrade pip
          pip install requests testrail google-api-python-client

      # ✅ Verify the virtual environment path
      - name: Verify venv path
        run: |
          ls -la .venv || echo ".venv not found"

      # ✅ Cache the virtual environment AFTER creating it
      - name: Cache Python Virtual Environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-python-3.10.16
          restore-keys: |
            venv-${{ runner.os }}-python-3.10

      # ✅ Archive the venv directory into a .tar file
      - name: Archive venv
        run: |
          tar -czf python-venv.tar.gz .venv

      # ✅ Upload the archive as an artifact
      - name: Upload Virtual Environment Archive
        uses: actions/upload-artifact@v4
        with:
          name: python-venv-tar
          path: python-venv.tar.gz
          if-no-files-found: error
