name: cafe_metrics123

on: workflow_dispatch

jobs:
  Setup_Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      # ✅ Create the virtual environment before cachinggg
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install requests testrail google-api-python-client

      # ✅ Cache after creating the environment
      - name: Cache Python Virtual Environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-python-3.10.16

      # ✅ Verify the environment exists
      - name: Verify venv path
        run: |
          ls -la .venv

      # ✅ Only upload the artifact if it exists
      - name: Upload Virtual Environment
        if: hashFiles('.venv/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: python-venv
          path: .venv
