name: cafe_metrics

on: workflow_dispatch

jobs:
  Setup_Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      - name: Cache Python Virtual Environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv1
          key: venv1-${{ runner.os }}-python-3.10.16

      - name: Save Cache (First Run)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: .venv1
          key: venv1-${{ runner.os }}-python-3.10.16     

      - name: Install Dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y zip tar
          python -m venv .venv1
          source .venv/bin/activate
          pip install --upgrade pip
          pip install requests testrail google-api-python-client

      # ✅ Archive both the venv and the repository into a single tarball (excluding the archive itself)
      - name: Archive venv and repo
        run: |
           tar -czf repo-and-venv.tar.gz .venv1 ./
      - name: Upload Repository and Virtual Environment
        uses: actions/upload-artifact@v4
        with:
          name: repo-and-venv
          path: repo-and-venv.tar.gz

  Clone_Repository:
    needs: Setup_Environment
    runs-on: ubuntu-latest
    steps:
      # ✅ Download the combined archive
      - name: Download Repository + venv
        uses: actions/download-artifact@v4
        with:
          name: repo-and-venv
          path: .

      # ✅ Extract the combined archive
      - name: Extract Repository + venv
        run: |
          tar -xzf repo-and-venv.tar.gz
          ls -la .venv
          ls -la

      # ✅ Use the virtual environment and run the script
      - name: Use Virtual Environment
        run: |
          source .venv/bin/activate
          ls -la
          cd allure_results || { echo "Folder not found"; exit 1; }
