name: Sequential Execution
#event to trigger on specific
on: [push]
env:
  GLOBAL_ENV_VAR: "This is a global environment variable"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test_report_name: test_results8
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Use global environment variable and secrets
        run: |
             echo "Global environment variable:$GLOBAL_ENV_VAR"    
             echo "Using secret KEY: ${{ secrets.KEY }}" 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          cd src
          python -m pytest sample.py --junitxml=test_results8/test_report.xml  # Save test results in XML
      - name: Upload test results as artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: test_results8
          path: src/test_results8/test_report.xml
        
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy runs after build
    steps:
      - name: get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: test_results8
      - name: Output contents
        run: ls
      - name: Deploy
        run: |
          echo "Deployment completed"
  success_notification:
    runs-on: ubuntu-latest
    needs: build  
    if: success()  # This ensures success_notification job runs only if the build job is successful
    steps:
      - name: Send success notification
        run: |
          echo "Build succeeded. Notifying the team"         
        
