name: Sequential Execution
#event to trigger
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          cd src
          python -m pytest sample.py --junitxml=test_results/test_report.xml  # Save test results in XML
      - name: Upload test results as artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: test_results
          path: src/test_results
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy runs after build
    steps:
      - name: Deploy
        run: |
          echo "Deployment completed"
