name: Python Playwright Test

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Checks out your code from GitHub

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can adjust the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        python -m playwright install  # Install Playwright browsers
        pip install allure-pytest  # Install allure-pytest for Allure integration

    - name: Install Allure CLI
      run: |
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.tgz | tar xzv
        sudo mv allure-2.19.0/bin/allure /usr/local/bin/allure  # Move allure binary to the PATH

    - name: Run tests
      run: pytest --alluredir=allure-results test_elements.py  # Generate Allure results

    - name: Generate Allure report
      run: |
        allure serve allure-results  # This will generate and serve the Allure report locally (you can use this for local inspection)
