name: Python Playwright Test

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt 
        python -m playwright install 
        pip install allure-pytest 

    - name: Run tests
      run: |
        pytest test_elements.py --alluredir=allure_results5

    - name: List Allure Results Directory
      run: ls -la allure_results5

    - name: Upload Allure results as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: allure-results 
        path: allure_results5

    - name: Generate Allure report
      run: |
        pip install allure-commandline  
        allure generate allure_results1 --clean -o allure-report  # Generate Allure report

    # - name: Deploy Allure report to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: gh-pages     
    #     publish_dir: allure-report     
    #     allow_empty_commit: true       
