name: Python Playwright Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt 
        python -m playwright install 
        pip install allure-pytest 

    - name: Run tests
      run: |
        pytest test_elements.py --alluredir=allure_results6

    - name: List Allure Results Directory
      run: ls -la allure_results6

    - name: Upload Allure results as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: allure-results 
        path: allure_results6

    - name: Install Allure commandline (Latest Version)
      run: |
        LATEST_ALLURE_VERSION=$(curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest | jq -r .tag_name)
        wget -qO- https://github.com/allure-framework/allure2/releases/download/$LATEST_ALLURE_VERSION/allure-$LATEST_ALLURE_VERSION.tgz | tar xvz -C /tmp
        sudo ln -s /tmp/allure-$LATEST_ALLURE_VERSION/bin/allure /usr/local/bin/allure

    - name: Generate Allure report
      run: |
        allure generate allure_results6 --clean -o allure-report


    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages     
        publish_dir: allure-report     
        allow_empty_commit: true       
    - name: Output Allure Report URL
      run: |
        echo "Allure Report is available at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allure-report/index.html"


