name: Python Playwright Test

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Checks out your code from GitHub

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can adjust the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        python -m playwright install  # Install Playwright browsers
        pip install allure-pytest  # Install allure-pytest for Allure integration

    - name: Run tests
      run: |
        pytest test_elements.py --alluredir=allure_results  # Generate Allure results

    - name: Upload Allure results as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: allure-results  # Name of the artifact
        path: allure_results  # Path to the Allure results directory

    - name: Generate Allure report
      run: |
        pip install allure-commandline  # Ensure allure-commandline is installed
        allure generate allure_results --clean -o allure-report  # Generate Allure report

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_branch: gh-pages         # This specifies the branch to push the report to (typically 'gh-pages' for GitHub Pages)
        folder: allure-report            # The folder that contains your Allure report
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided GitHub token to authenticate the push
