name: Python Playwright Test

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Checks out your code from GitHub

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can adjust the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        python -m playwright install  # Install Playwright browsers

    - name: Run tests
      run: pytest test_elements.py  # Run the test using pytest
