name: Parallel, Sequential, and Matrix Execution

on: workflow_dispatch

jobs:
  parallel-1:
    runs-on: ubuntu-latest
    steps:
      - name: Parallel Job 1
        run: echo "Running Parallel Job 1"

  parallel-2:
    runs-on: ubuntu-latest
    steps:
      - name: Parallel Job 2
        run: echo "Running Parallel Job 2"

  sequential:
    runs-on: ubuntu-latest
    needs: [parallel-1, parallel-2]
    steps:
      - name: Sequential Job
        run: echo "Running Sequential Job"

  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.8, 3.9]
    steps:
      - name: Matrix Job
        run: echo "Running on ${{ matrix.os }} with Python ${{ matrix.python }}"
